### PR TITLE
Added isTracking method to ViveController. Verifying tracking before updating matrix or button states.

### PR DESCRIPTION
**Pull request by spiderworm**
#1

### CODE REVIEW

**Comment by mrdoob** [comment]
Interesting. I "fixed" this just today:

https://github.com/mrdoob/three.js/commit/a17c4c5ea01c241cc0a0dcc8b71ac295a0f5ac4f

Undecided about which approach I like better. Yours hide the controller, right?

**Comment by spiderworm** [comment]
Yes. With my change, if the controller stops tracking, it disappears from the render rather than freezing in place.

Off topic: I assume you've seen the following hilarious utility? http://zz85.github.io/mrdoobapproves/

**Comment by spiderworm** [comment]
Ah, I didn't realize three.js contains the "upstream" version of ViveController.js. Should I submit my PR there instead?

**Comment by mrdoob** [comment]
> Off topic: I assume you've seen the following hilarious utility? http://zz85.github.io/mrdoobapproves/

Yes! 😀

> Ah, I didn't realize your three.js repo contains the "upstream" version of ViveController.js. Should I submit my PR there instead?

Yes please!

**Comment by mrdoob** [comment]
Does `isTracking` need to be public? Are you using it from outside?

**Comment by spiderworm** [comment]
> Does isTracking need to be public? Are you using it from outside?

No and not yet. But it seems useful to be able to check the tracking status from outside (to display a message to the user or do something else useful when tracking is lost) and I'm 90% sure that's something I'm going to be wanting to use within the next 72 hours.

I'll make a few more modifications to cache the tracking status, raise events when tracking is gained/lost, submit my PR to your three.js repo, and then we'll see what you think :)

**Comment by spiderworm** [comment]
@mrdoob New PR here: https://github.com/mrdoob/three.js/pull/9605

**Pull request closed without merging**
